### PR TITLE
Argentina patch #448

### PR DESCRIPTION
**Pull request by iadawn**

### CODE REVIEW

**Comment by shawna-slh** [comment]
published. https://www.w3.org/WAI/policies/argentina/

**Comment by shawna-slh** [comment]
Hey @iadawn & @mhansma96

There extra commas in the JSON, which caused extra filters to be created. So (in addition to fixing this one :-) we'll need to be careful of that for further updates to the JSON files and also do QA checks for it.

image

**Comment by shawna-slh** [comment]
I went ahead and [fixed the comma-os](https://github.com/w3c/wai-policies-prototype/pull/479) since I'm pointing to this tonight in a social media reply .

**Comment by shawna-slh** [comment]
However, I noted a new potential issue on [the listing](https://www.w3.org/WAI/policies/argentina/) : shouldn't it have link(s) at the top under "Official law/policy pages"?

**Comment by iadawn** [comment]
The trailing comma issue should be fixed. It was something I spotted in the submissions and added a fix to the submission.php. I must have missed it in the Argentina test. Any newly created submissions should not have this issue but all the previous submissions in the Issues list will have it. This should not be an issue if these are all to be recreated.

**Comment by iadawn** [comment]
> However, I noted a new potential issue on [the listing](https://www.w3.org/WAI/policies/argentina/) : shouldn't it have link(s) at the top under "Official law/policy pages"?

I have taken a look into this and there are a couple of issues.

* The current submission form created tabs in the JSON which caused a problem. - Fixed
* The current submission form did not specify the langage for the main policy url. This means that it isn't picked up to create the entry in the section for "Official law/policy page" - Fixed
* The current submission form assumes that the "Official law/policy page" is in English. There is no way via the form to specify a different language.
* However, if you do specify a different langage then the grey header is not populated with the policy name as this seems to only use the 'en' version.

@shawna-slh Need to have a quick chat about the last two items

**Comment by shawna-slh** [comment]
hey @iadawn I merged and published:
* https://github.com/w3c/wai-policies-prototype/pull/480
* https://github.com/w3c/wai-website-theme/pull/49

Unfortunately it didn't fix the issue :(

**Comment by iadawn** [comment]
Might have taken some time to clear the cache but it seems to be working now

**Pull request merged**
