### PR TITLE
added Luxembourg

### PR DESCRIPTION
**Pull request by AlainVagner**

### CODE REVIEW

**Comment by shawna-slh** [comment]
Thank you @AlainVagner ! We are behind on updating this resource. We hope to get to this in the next couple of months.

**Comment by biou** [comment]
No Problem! Hope this helps :)

**Comment by AlainVagner** [comment]
No problem @shawna-slh ! If you need more information, feel free to contact me.
I also informed the [EU Web Accessibility Expert Group (WADEX)](https://digital-strategy.ec.europa.eu/en/policies/web-accessibility-expert-group), that this page will be updated. I hope you will get updates from other EU member states.

**Review by EricVelleman — COMMENTED** [review]
Ok for me
Eric

**Pull request merged**
