### PR TITLE
Add Argentina

### PR DESCRIPTION
**Pull request by yatil**

### CODE REVIEW

**Comment by yatil** [comment]
Deploy preview for *wai-policies-prototype* processing.

Building with commit e88e21286dbddaafa74d3e69bb1c81071b13791a

https://app.netlify.com/sites/wai-policies-prototype/deploys/5e43edb63879f200084b8fb4

**Comment by yatil** [comment]
@AndrewArch This should address #368 and #358.

**Important:** This is still missing the English translation of the Law/Policy. ([Line 13](https://github.com/w3c/wai-policies-prototype/pull/383/files#diff-124fb121654871e7c33656085659822bR13))

**Comment by slhenry** [comment]
Hi @AndrewArch 

I spent some time reading through this material:
> Web Accessibility Repository
> Spanish: Repositorio del Equipo de Accesibilidad Web (español)
> The Web Accessibility Repository on GithHub contains many resources as guides, posters, technical recommendations, etc.

It seems to be much broader than directly clarifying the law. I think it is outside the scope of what we should include in this Laws and Policies List.

Shall we talk about it?

**Comment by yatil** [comment]
Closing for no activity in over 2 years.

**Pull request closed without merging**
