### PR TITLE
Revert "create aland.md"

### PR DESCRIPTION
**Pull request by iadawn**
Reverts w3c/wai-policies-prototype#447

### CODE REVIEW

**Comment by shawna-slh** [comment]
@iadawn Hey Kevin. The revert created a PR for the revert, then you still needed to merge it. :-)

**Comment by iadawn** [comment]
Says it is merged... hmm

**Comment by shawna-slh** [comment]
I merged it just now

**Comment by iadawn** [comment]
That would explain it then 😁

**Pull request merged**
